### ISSUE TITLE
Changes to when Card Move event is triggered.

### ISSUE THREAD

**Issue by Blackmoor** [octgn/OCTGN#1202]
(Test version)

The proposal to NOT trigger the event for the player doing the move will break my game in several important ways. I'd like to ask that this feature not be implemented.
Why? .... because I have modules in my code that are independent. They should not need to know or care that another module or class in my code is triggering on something happening when a card state changes (i.e. in this case is moved).

If you implement this then I would need to add calls to the event triggers myself in other modules that they should have no knowledge of. This really does break the design principles I have coded to and would require a big rewrite and I certainly can't commit completing this (and test it all) by the proposed go live date of the 22nd.

**Comment by brine** [comment]
OK so from what I've seen, the 3.1.0.1 version of the OnMoveCard(s) and OnScriptedMoveCard(s) events actually have use for the isScriptedMove parameter, as that paremeter is the decision point for which event is used.

I was working on #1374 and was going to need to create a 3.1.0.2 API version in order to add the isFaceUp parameter.  The alternative is I repurpose the isScriptedMove parameter to oldIsFaceUp, which would keep the same number of parameters and not break compatibility.  I prefer the latter, as the former has no scripting significance.
