### ISSUE TITLE
Resetting a game doesn't reset local variables

### ISSUE THREAD

**Issue by Wirox** [octgn/OCTGN#1864]
When a game is reset via the `Game -> Reset` option, local variables (i.e. global Python variables) aren't actually restored to their default values.

This is one of the ways to reproduce the issue in MtG (below is presented the Python console log):
```
>>> diesides
20
>>> diesides = 123
```
*reset the game*
```
>>> diesides
123
```

**Comment by kellyelton** [comment]
This is by design.

If you'd like to reset python variables you can do that in the [OnGameStarted ](https://github.com/octgn/OCTGN/wiki/OCTGN-Python-3.1.0.2-API-Reference#ongamestarted)event(or [OnGameStart ](https://github.com/octgn/OCTGN/wiki/OCTGN-Python-3.1.0.1-API-Reference#ongamestart)in older script versions than 3.1.0.2)
