### ISSUE TITLE
Allow non-default markers to be renamed

### ISSUE THREAD

**Issue by db0** [octgn/OCTGN#446]
At the moment, I can put one of the default markers with a custom name, which is very useful for marking when a card has gotten an effect from another card. I would like the same functionality to be extended to the custom markers that are installed in sets.

This would be useful when I want to put a more explanatory counter, while also retaining the "link" (via the name) to the original card.

A more specific example, I have a card which gives +1 bonus to another card. It also gives a few other smaller benefits to any card that has this +1. Now I can either put a generic and named counter on the target card, or I can put special +1 marker I have, but it will always have its set name, whatever it is on the set definition. I want to have the best of both worlds, the custom Icon and the specific name

**Comment by brine** [comment]
so this was added, eh?

**Comment by brine** [comment]
8 months later I finally tested this, there's still some work that needs to be done because you can't assign the same marker GUID to multiple cards and have different names between them.

If I add a marker ("jimmy", "33333-3") to a card, and add ("bobby", "33333-3") to another card, OCTGN thinks those are the same marker and will act funny when you try to interact with them seperately.  We need to treat those two markers as unique objects, but they just happen to share a GUID target.
